fail_fast: true
repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.8.3
    hooks:
      # Run the linter.
      - id: ruff
        args: [ --fix ]
      # Run the formatter.
      - id: ruff-format
  - repo: local
    hooks:
      - id: add-ticket-number
        name: Add Ticket Number to Commit Message
        entry: ./scripts/add-ticket-number.sh
        language: system
        stages: [commit-msg]
ci:
    autofix_prs: false
